StockTracker/Pages/AppInfo.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StockTracker.Pages
{
    public class AppInfoModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

StockTracker/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace StockTracker.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

StockTracker/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using StockTracker.Injections;
using System.Formats.Asn1;
using StockTracker.Models;
using System.Text;
using System.Runtime.CompilerServices;

namespace StockTracker.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IStockAPI _stockAPI;
        private readonly INewsAPI _newsAPI;

        public IndexModel(ILogger<IndexModel> logger, IStockAPI stockClient, INewsAPI newsAPI)
        {
            _logger = logger;
            _stockAPI = stockClient;
            _newsAPI = newsAPI;
        }

        //Method for merging int lists
        public List<int> mergeLists(List<int> first, List<int> second)
        {
            List<int> result = new List<int>();

            foreach(var item in first)
            {
                result.Add(item);
            }
            foreach (var item in second)
            {
                result.Add(item);
            }
            return result;
        }

        public async Task OnGet()
        {
            tickers = await _stockAPI.getExampleTickers();
            stockDataList = await _stockAPI.getStockValues(DateTime.Now.AddDays(-3), "TSLA", "minute");
            performanceData = _stockAPI.getPerformanceDict(stockDataList);
            selectedTickerFullName = await _stockAPI.tickerFullName(selectedTicker);
            HttpContext.Session.SetString("timespan", "1D");
            improvement = (performanceData["improvement"] == "1") ? "text-success" : "text-danger";

            increaseIntervals = _stockAPI.getIncreaseIntervals(stockDataList);
            decreaseIntervals = _stockAPI.getDecreaseIntervals(stockDataList);

            generalNews = await _newsAPI.GeneralNews(selectedTicker, DateTime.Now);

            List<int> intervalsToShow = new List<int>();
            intervalsToShow = mergeLists(increaseIntervals, decreaseIntervals);

            intervalNews = await _newsAPI.IntervalNews(selectedTicker, intervalsToShow, stockDataList);
        }

        public async Task<IActionResult> OnPostTickerSelection()
        {
            tickers = await _stockAPI.getExampleTickers();
            selectedTickerFullName = await _stockAPI.tickerFullName(selectedTicker);

            HttpContext.Session.SetString("ticker", selectedTicker);

            if (HttpContext.Session.TryGetValue("timespan", out byte[] tickerBytes))
            {

                Timespan = HttpContext.Session.GetString("timespan");
            }
            else
            {
                Timespan = "1D";
            }

            DateTime start = DateTime.Now;
            string timespan = "minute";
            switch (Timespan)
            {
                case "1D":
                    start = DateTime.Now.AddDays(-3);
                    timespan = "minute";
                    day = "btn-info"; week = ""; year = ""; month = "";
                    break;
                case "1W":
                    start = DateTime.Now.AddDays(-7);
                    timespan = "hour";
                    day = ""; week = "btn-info"; year = ""; month = "";
                    break;
                case "1M":
                    start = DateTime.Now.AddMonths(-1);
                    timespan = "hour";
                    day = ""; week = ""; year = ""; month = "btn-info";
                    break;
                case "1Y":
                    start = DateTime.Now.AddYears(-1);
                    timespan = "week";
                    day = ""; week = ""; year = "btn-info"; month = "";
                    break;
            }
            
            
            stockDataList = await _stockAPI.getStockValues(start, selectedTicker, timespan);
            performanceData = _stockAPI.getPerformanceDict(stockDataList);
            improvement = (performanceData["improvement"] == "1") ? "text-success" : "text-danger";
            increaseIntervals = _stockAPI.getIncreaseIntervals(stockDataList);
            decreaseIntervals = _stockAPI.getDecreaseIntervals(stockDataList);
            generalNews = await _newsAPI.GeneralNews(selectedTicker, DateTime.Now);
            List<int> intervalsToShow = new List<int>();
            intervalsToShow = mergeLists(increaseIntervals, decreaseIntervals);

            intervalNews = await _newsAPI.IntervalNews(selectedTicker, intervalsToShow, stockDataList);
            return Page();
        }

        public async Task<IActionResult> OnPostTimespan()
        {
            tickers = await _stockAPI.getExampleTickers();
 
            if (HttpContext.Session.TryGetValue("ticker", out byte[] tickerBytes))
            {
               
                selectedTicker = HttpContext.Session.GetString("ticker");
            }
            else
            {
                selectedTicker = "TSLA";
            }

            selectedTickerFullName = await _stockAPI.tickerFullName(selectedTicker);

            string ticker = selectedTicker;
            string timespan = Timespan;
            switch (timespan)
            {
                case "1D":
                    stockDataList = await _stockAPI.getStockValues(DateTime.Now.AddDays(-3), ticker, "minute");
                    HttpContext.Session.SetString("timespan", "1D");
                    day = "btn-info"; week = ""; year = ""; month = "";
                    break;
                case "1W":
                    stockDataList = await _stockAPI.getStockValues(DateTime.Now.AddDays(-7), ticker, "hour");
                    HttpContext.Session.SetString("timespan", "1W");
                    day = ""; week = "btn-info";  year = ""; month = "";
                    break;
                case "1M":
                    stockDataList = await _stockAPI.getStockValues(DateTime.Now.AddMonths(-1), ticker, "hour");
                    HttpContext.Session.SetString("timespan", "1M");
                    day = ""; week = ""; year = ""; month = "btn-info";
                    break;
                case "1Y":
                    stockDataList = await _stockAPI.getStockValues(DateTime.Now.AddYears(-1), ticker, "week");
                    HttpContext.Session.SetString("timespan", "1Y");
                    day = ""; week = ""; year = "btn-info"; month = "";
                    break;
            }

            performanceData = _stockAPI.getPerformanceDict(stockDataList);
            improvement = (performanceData["improvement"] == "1") ? "text-success" : "text-danger";
            increaseIntervals = _stockAPI.getIncreaseIntervals(stockDataList);
            decreaseIntervals = _stockAPI.getDecreaseIntervals(stockDataList);
            generalNews = await _newsAPI.GeneralNews(selectedTicker, DateTime.Now);
            List<int> intervalsToShow = new List<int>();
            intervalsToShow = mergeLists(increaseIntervals, decreaseIntervals);

            intervalNews = await _newsAPI.IntervalNews(selectedTicker, intervalsToShow, stockDataList);
            return Page();
        }

        [BindProperty]
        public string selectedTicker { get; set; } = "TSLA";

        [BindProperty]
        public string Timespan { get; set; }


        public List<int> increaseIntervals { get; set; } = new List<int>();
        public List<int> decreaseIntervals { get; set; } = new List<int>();
        public string selectedTickerFullName { get; set; } = "Tesla, Inc. Common Stock";

        public List<string> tickers {  get; set; }
        public List <StockData> stockDataList { get; set; }
        public Dictionary<string, string> performanceData { get; set; }


        //List for general news... just current news about selected stock from current date
        public List<ArticleInfo> generalNews { get; set; } = new List<ArticleInfo> {
        new ArticleInfo {
            Title = "Something went wrong",
            Description = "",
            Author = "",
            publishedAt = DateTime.Now,
            Url = ""
        }};

        //represents list of news that are from those dates that the stock was changing the most 
        public List<ArticleInfo> intervalNews { get; set; } = new List<ArticleInfo> {
        new ArticleInfo {
            Title = "Something went wrong",
            Description = "",
            Author = "",
            publishedAt = DateTime.Now,
            Url = ""
        }};

        public string improvement { get; set; } = "";

        public string day { get; set; } = "btn-info";
        public string year { get; set; }
        public string month { get; set; }
        public string week { get; set; }
}
}

StockTracker/Pages/AppInfo.cshtml
@page
@model StockTracker.Pages.AppInfoModel

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="text-center">
                <h1 class="display-4">Welcome to Stock Tracker</h1>
                <p class="lead">Stock Tracker is a powerful tool for monitoring stock performance and staying updated with relevant news.</p>
            </div>
            <div>
                <h2 class="mb-4">Key Features:</h2>
                <ul class="list-group">
                    <li class="list-group-item"><strong>Interactive Stock Graph:</strong> Click on the Stock Tracker text at the top left corner to access an interactive graph displaying the performance of a selected stock. Easily switch between different stocks by entering their ticker symbols.</li>
                    <li class="list-group-item"><strong>Customizable Time Intervals:</strong> Choose from predefined time intervals such as 1 day, 1 week, 1 month, or 1 year to view historical stock data.</li>
                    <li class="list-group-item"><strong>Highlighted Trends:</strong> The stock graph highlights significant growth or decline periods with dashed green or red lines, helping users identify key trends at a glance.</li>
                    <li class="list-group-item"><strong>General News Section:</strong> Stay informed with the latest news related to the stock market and general finance. News items are updated regularly to keep you informed.</li>
                    <li class="list-group-item"><strong>Interval News:</strong> Dive deeper into the news relevant to your selected stock by accessing interval news. These news items are curated based on dates when significant changes in the stock value occurred.</li>
                </ul>
            </div>
            <div class="text-center mt-4">
                <p class="lead">Experience the convenience of tracking stocks and staying informed with Stock Tracker today!</p>
            </div>
        </div>
    </div>
</div>

StockTracker/Pages/Index.cshtml
@page
@model StockTracker.Pages.IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <div class="" style="width: 100%;">
        <form method="post" asp-page-handler="TickerSelection">
             <div class="d-flex flex-nowrap overflow-auto">
                 @foreach(var ticker in Model.tickers)
                 {
                     <input type="submit" name="selectedTicker" value="@ticker" class="btn-light px-4 py-2 rounded-0 btn border-bottom-0 border-top-0 border-dark flex-grow-1 mr-2" />
                 }

             </div>
        </form>
    </div>

</div>

<div class="p-5">
    <form method="post" asp-page-handler="TickerSelection">
        <label for="ticker" class="form-label">
            If you want to select different stock write down its ticker (TSLA, AAPL...):
        </label>
        <br />
        <input class="form-control" type="text" placeholder="ticker" name="selectedTicker" />
        <br />
        <input class="btn btn-primary" type="submit" value="submit" />
    </form>

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h1>@Model.selectedTicker - @Model.selectedTickerFullName</h1>
            </div>
            <div class="col-md-6">
                <form method="post" class="text-end" asp-page-handler="Timespan">
                    <input type="submit" value="1Y" class="btn btn-primary @Model.year" name="Timespan" />
                    <input type="submit" value="1M" class="btn btn-primary @Model.month" name="Timespan" />
                    <input type="submit" value="1W" class="btn btn-primary @Model.week" name="Timespan" />
                    <input type="submit" value="1D" class="btn btn-primary @Model.day" name="Timespan" />
                </form>
            </div>
        </div>
    </div>

    <div class="container" style="height: 100%;">
        <div class="row">
            <div class="col-md-3 border p-3 d-flex flex-column align-items-start">
                <h2 class="mb-4">Performance [USD]</h2>
                
                <p class="mb-2"><strong>Starting Price:</strong> @Model.performanceData["Starting Price"] [USD]</p>
                <p class="mb-2"><strong>Current Price:</strong> @Model.performanceData["Current Price"] [USD]</p>
                <p class="mb-2"><strong>Lowest Price:</strong> @Model.performanceData["Lowest Price"] [USD]</p>
                <p class="mb-2"><strong>Highest Price:</strong> @Model.performanceData["Highest Price"] [USD]</p>
                <p class="mb-2"><strong>Price Difference: <span class="@Model.improvement">@Model.performanceData["Price Difference"] [USD]</span></strong> </p>
                <p class="mb-2"><strong>Improvement Percentage: <span class="@Model.improvement">@Model.performanceData["Improvement Percentage"]</span></strong> </p>
                <p class="mb-2"><strong>Starting Date:</strong> @Model.performanceData["Starting Date"]</p>
                <p class="mb-2"><strong>Current Date:</strong> @Model.performanceData["Current Date"]</p>
               
            </div>

            <div class="col-md-9">
                <div class="border p-3">
                    <canvas id="StockChart"></canvas>
                </div>
            </div>
        </div>

    </div>

    <div class="container mt-5">
        <h2>General News</h2>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Author</th>
                        <th>Published At</th>
                        <th>Link</th>
                    </tr>
                </thead>
                <tbody>
                    @for (var i = 0; i < Math.Min(3, @Model.generalNews.Count); i++)
                    {
                        var article = @Model.generalNews[i];
                        <tr>
                            <td>@article.Title</td>
                            <td>@article.Description</td>
                            <td>@article.Author</td>
                            <td>@article.publishedAt.ToString("yyyy-MM-dd HH:mm:ss")</td>
                            <td><a href="@article.Url" target="_blank">Read more</a></td>
                        </tr>
                    }

                     @for (var i = 3; i < @Model.generalNews.Count; i++)
                     {
                         var article = @Model.generalNews[i];
                         <tr class="moreRows d-none">
                            <td>@article.Title</td>
                            <td>@article.Description</td>
                            <td>@article.Author</td>
                            <td>@article.publishedAt.ToString("yyyy-MM-dd HH:mm:ss")</td>
                            <td><a href="@article.Url" target="_blank">Read more</a></td>
                         </tr>
                     }

                </tbody>
            </table>
        </div>
        <!-- Show more and less buttons -->
        <button class="btn btn-primary" id="showMoreButton">Show more</button>
        <button class="btn btn-primary bg-danger" id="showLessButton">Show less</button>

        <h2>Interval News</h2>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Author</th>
                        <th>Published At</th>
                        <th>Link</th>
                    </tr>
                </thead>
                <tbody>
                    @for (var i = 0; i < Math.Min(3, @Model.intervalNews.Count); i++)
                    {
                        var article = @Model.intervalNews[i];
                        <tr>
                            <td>@article.Title</td>
                            <td>@article.Description</td>
                            <td>@article.Author</td>
                            <td>@article.publishedAt.ToString("yyyy-MM-dd HH:mm:ss")</td>
                            <td><a href="@article.Url" target="_blank">Read more</a></td>
                        </tr>
                    }

                    @for (var i = 3; i < @Model.intervalNews.Count; i++)
                    {
                        var article = @Model.intervalNews[i];
                        <tr class="moreRowsIntervals d-none">
                            <td>@article.Title</td>
                            <td>@article.Description</td>
                            <td>@article.Author</td>
                            <td>@article.publishedAt.ToString("yyyy-MM-dd HH:mm:ss")</td>
                            <td><a href="@article.Url" target="_blank">Read more</a></td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>

        <!-- Show more and less buttons -->
        <button class="btn btn-primary" id="showMoreButtonIntervals">Show more</button>
        <button class="btn btn-primary bg-danger" id="showLessButtonIntervals">Show less</button>

        
    </div>

</div>

<script>
    // JavaScript to handle show more button GENERAL
    document.getElementById('showMoreButton').addEventListener('click', function () {
        var moreRows = document.querySelectorAll('.moreRows');
        moreRows.forEach(function (row) {
            row.classList.remove('d-none');
        });
    });

    // JavaScript to handle show less button GENERAL
    document.getElementById('showLessButton').addEventListener('click', function () {
        var moreRows = document.querySelectorAll('.moreRows');
        moreRows.forEach(function (row) {
            row.classList.toggle('d-none');
        });
    });

    // JavaScript to handle show more button INTERVAL
    document.getElementById('showMoreButtonIntervals').addEventListener('click', function () {
        var moreRows = document.querySelectorAll('.moreRowsIntervals');
        moreRows.forEach(function (row) {
            row.classList.remove('d-none');
        });
    });

    // JavaScript to handle show less button INTERVAL
    document.getElementById('showLessButtonIntervals').addEventListener('click', function () {
        var moreRows = document.querySelectorAll('.moreRowsIntervals');
        moreRows.forEach(function (row) {
            row.classList.toggle('d-none');
        });
    });


    var stockData = [
    @foreach (var item in Model.stockDataList)
    {
        <text>
            {
                dateTime: '@item.DateTime',
                ticker: '@item.Ticker',
                price: '@item.Price'
            },
        </text>
    }
    @if (Model.stockDataList.Count > 0)
    {
        { }
    }
    ];

    var chartData = {
        labels: stockData.map(data => data.dateTime),
        datasets: [{
            label: 'Stock Price',
            borderColor: 'rgb(75, 192, 192)',
            data: stockData.map(data => parseFloat(data.price.replace(',', '.'))),
            fill: false,
            pointRadius: 0
        }]
    };


    var options = {
        responsive: true,
        maintainAspectRatio: true,
        scales: {
            x: {
                ticks: {
                    callback: function (val, index, values) {
                        let lastIndex = values.length - 1;
                        let middleIndex;

                        if(values.length % 2 == 0){
                            middleIndex = values.length / 2;
                        }
                        else{
                            middleIndex = (values.length - 1) / 2;
                        } 
                        if (index === 0 || index === lastIndex) {
                            
                            return this.getLabelForValue(val);
                        } else {
                            return '';
                        }
                    },
                    autoSkip: false,
                    maxRotation: 0,
                },
                type: 'category',
                labels: chartData.labels,
                maxTicksLimit: 2, 
                autoSkip: true,
                maxRotation: 0,
                title: {
                    display: true,
                    text: 'Price [USD]'
                },
                border: {
                    display: false,
                    dash: [6,6]
                },
                grid:{  
                    lineWidth: 2.5,
                    color: (context) => {
                        
                        if (context.tick.value === @Model.increaseIntervals[0] || context.tick.value === @Model.increaseIntervals[1] || context.tick.value === @Model.increaseIntervals[2]) {
                            return "green"
                        }
                        else if (context.tick.value === @Model.decreaseIntervals[0] || context.tick.value === @Model.decreaseIntervals[1] || context.tick.value === @Model.decreaseIntervals[2]) {
                            return "red";
                        }
                    },
                    tickBorderDash: [1, 10]
                },
            },
            y: {
                title: {
                    display: true,
                    text: 'TimeLine'
                },
                beginAtZero: false,
                min: parseInt(Math.min(...chartData.datasets[0].data) - 5), 
                max: parseInt(Math.max(...chartData.datasets[0].data) + 5), 
                ticks: {
                    type: 'linear', 
                    ticks: {
                        callback: function (value, index, values) {
                            return Math.pow(10, value);
                        }
                    }
                },
                grid: {
                    color: function () {
                        return "#000000"
                    }
                },

            }
        }
    };

    var ctx = document.getElementById('StockChart').getContext('2d');

    var myLineChart = new Chart(ctx, {
        type: 'line',
        data: chartData,
        options: options
    });
</script>